name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

env:
  JAVA_VERSION: 11

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.1.0
        with:
          gradle-home-cache-cleanup: true
      - run: ./gradlew --version

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4.1.0

      - name: Cache Gradle dependencies
        uses: actions/cache@v4.1.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            Pods
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.4.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.1.0

      - name: Build and Run Tests
        run: ./gradlew build -s

      - name: Kill the Simulator
        run: ./gradlew simulatorKill -s

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.0
        if: github.repository == 'jaredsburrows/ios-gradle-swift-app-template' && github.ref == 'refs/heads/master'
        with:
          name: ios-gradle-swift-app-template-${{ github.workflow }}-${{ github.run_id }}
          path: |
            build/sym/Debug-iphonesimulator/ios-gradle-swift-app-template.app
