name: build

on: [push, pull_request]

jobs:
  ios:
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build and Run Tests
        run: ./gradlew clean build -s --scan

      - name: Kill the Simulator
        run: ./gradlew simulatorKill -s --scan

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ios-gradle-objc-app-template-${{ github.workflow }}-${{ github.run_id }}
          path: |
            ios-gradle-objc-app-template/build/outputs
            ios-gradle-objc-app-template/build/reports
            ios-gradle-objc-app-template/build/test-results
          if-no-files-found: warn

